// Auto-generated component registry for problem MDX components

export const problemComponents = {
  '1-two-sum': () => import('./1-two-sum.mdx'),
  '1000-minimum-cost-to-merge-stones': () => import('./1000-minimum-cost-to-merge-stones.mdx'),
  '1011-capacity-to-ship-packages-within-d-days': () => import('./1011-capacity-to-ship-packages-within-d-days.mdx'),
  '102-binary-tree-level-order-traversal': () => import('./102-binary-tree-level-order-traversal.mdx'),
  '105-construct-binary-tree-from-preorder-and-inorder-traversal': () => import('./105-construct-binary-tree-from-preorder-and-inorder-traversal.mdx'),
  '1094-car-pooling': () => import('./1094-car-pooling.mdx'),
  '1143-longest-common-subsequence': () => import('./1143-longest-common-subsequence.mdx'),
  '1162-as-far-from-land-as-possible': () => import('./1162-as-far-from-land-as-possible.mdx'),
  '120-triangle': () => import('./120-triangle.mdx'),
  '121-best-time-to-buy-and-sell-stock': () => import('./121-best-time-to-buy-and-sell-stock.mdx'),
  '122-best-time-to-buy-and-sell-stock-ii': () => import('./122-best-time-to-buy-and-sell-stock-ii.mdx'),
  '123-best-time-to-buy-and-sell-stock-iii': () => import('./123-best-time-to-buy-and-sell-stock-iii.mdx'),
  '1235-maximum-profit-in-job-scheduling': () => import('./1235-maximum-profit-in-job-scheduling.mdx'),
  '124-binary-tree-maximum-path-sum': () => import('./124-binary-tree-maximum-path-sum.mdx'),
  '1249-minimum-remove-to-make-valid-parentheses': () => import('./1249-minimum-remove-to-make-valid-parentheses.mdx'),
  '127-word-ladder': () => import('./127-word-ladder.mdx'),
  '1275-find-winner-on-a-tic-tac-toe-game': () => import('./1275-find-winner-on-a-tic-tac-toe-game.mdx'),
  '1293-shortest-path-in-a-grid-with-obstacles-elimination': () => import('./1293-shortest-path-in-a-grid-with-obstacles-elimination.mdx'),
  '133-clone-graph': () => import('./133-clone-graph.mdx'),
  '136-single-number': () => import('./136-single-number.mdx'),
  '1406-stone-game-iii': () => import('./1406-stone-game-iii.mdx'),
  '141-linked-list-cycle': () => import('./141-linked-list-cycle.mdx'),
  '142-linked-list-cycle-ii': () => import('./142-linked-list-cycle-ii.mdx'),
  '144-binary-tree-preorder-traversal': () => import('./144-binary-tree-preorder-traversal.mdx'),
  '145-binary-tree-postorder-traversal': () => import('./145-binary-tree-postorder-traversal.mdx'),
  '146-lru-cache': () => import('./146-lru-cache.mdx'),
  '15-3sum': () => import('./15-3sum.mdx'),
  '1510-stone-game-iv': () => import('./1510-stone-game-iv.mdx'),
  '1514-path-with-maximum-probability': () => import('./1514-path-with-maximum-probability.mdx'),
  '152-maximum-product-subarray': () => import('./152-maximum-product-subarray.mdx'),
  '153-find-minimum-in-rotated-sorted-array': () => import('./153-find-minimum-in-rotated-sorted-array.mdx'),
  '1547-minimum-cost-to-cut-a-stick': () => import('./1547-minimum-cost-to-cut-a-stick.mdx'),
  '1563-stone-game-v': () => import('./1563-stone-game-v.mdx'),
  '1570-dot-product-of-two-sparse-vectors': () => import('./1570-dot-product-of-two-sparse-vectors.mdx'),
  '1584-min-cost-to-connect-all-points': () => import('./1584-min-cost-to-connect-all-points.mdx'),
  '1590-make-sum-divisible-by-p': () => import('./1590-make-sum-divisible-by-p.mdx'),
  '162-find-peak-element': () => import('./162-find-peak-element.mdx'),
  '1631-path-with-minimum-effort': () => import('./1631-path-with-minimum-effort.mdx'),
  '188-best-time-to-buy-and-sell-stock-iv': () => import('./188-best-time-to-buy-and-sell-stock-iv.mdx'),
  '191-number-of-1-bits': () => import('./191-number-of-1-bits.mdx'),
  '198-house-robber': () => import('./198-house-robber.mdx'),
  '20-valid-parentheses': () => import('./20-valid-parentheses.mdx'),
  '200-number-of-islands': () => import('./200-number-of-islands.mdx'),
  '207-course-schedule': () => import('./207-course-schedule.mdx'),
  '208-implement-trie-prefix-tree': () => import('./208-implement-trie-prefix-tree.mdx'),
  '210-course-schedule-ii': () => import('./210-course-schedule-ii.mdx'),
  '211-design-add-and-search-words-data-structure': () => import('./211-design-add-and-search-words-data-structure.mdx'),
  '212-word-search-ii': () => import('./212-word-search-ii.mdx'),
  '213-house-robber-ii': () => import('./213-house-robber-ii.mdx'),
  '2140-solving-questions-with-brainpower': () => import('./2140-solving-questions-with-brainpower.mdx'),
  '2145-count-the-hidden-sequences': () => import('./2145-count-the-hidden-sequences.mdx'),
  '215-kth-largest-element-in-an-array': () => import('./215-kth-largest-element-in-an-array.mdx'),
  '22-generate-parentheses': () => import('./22-generate-parentheses.mdx'),
  '238-product-of-array-except-self': () => import('./238-product-of-array-except-self.mdx'),
  '2402-meeting-rooms-iii': () => import('./2402-meeting-rooms-iii.mdx'),
  '252-meeting-rooms': () => import('./252-meeting-rooms.mdx'),
  '253-meeting-rooms-ii': () => import('./253-meeting-rooms-ii.mdx'),
  '256-paint-house': () => import('./256-paint-house.mdx'),
  '265-paint-house-ii': () => import('./265-paint-house-ii.mdx'),
  '279-perfect-squares': () => import('./279-perfect-squares.mdx'),
  '287-find-the-duplicate-number': () => import('./287-find-the-duplicate-number.mdx'),
  '297-serialize-and-deserialize-binary-tree': () => import('./297-serialize-and-deserialize-binary-tree.mdx'),
  '3-longest-substring-without-repeating-characters': () => import('./3-longest-substring-without-repeating-characters.mdx'),
  '300-longest-increasing-subsequence': () => import('./300-longest-increasing-subsequence.mdx'),
  '301-remove-invalid-parentheses': () => import('./301-remove-invalid-parentheses.mdx'),
  '311-sparse-matrix-multiplication': () => import('./311-sparse-matrix-multiplication.mdx'),
  '312-burst-balloons': () => import('./312-burst-balloons.mdx'),
  '32-longest-valid-parentheses': () => import('./32-longest-valid-parentheses.mdx'),
  '322-coin-change': () => import('./322-coin-change.mdx'),
  '325-maximum-size-subarray-sum-equals-k': () => import('./325-maximum-size-subarray-sum-equals-k.mdx'),
  '33-search-in-rotated-sorted-array': () => import('./33-search-in-rotated-sorted-array.mdx'),
  '34-find-first-and-last-position-of-element-in-sorted-array': () => import('./34-find-first-and-last-position-of-element-in-sorted-array.mdx'),
  '347-top-k-frequent-elements': () => import('./347-top-k-frequent-elements.mdx'),
  '348-design-tic-tac-toe': () => import('./348-design-tic-tac-toe.mdx'),
  '35-search-insert-position': () => import('./35-search-insert-position.mdx'),
  '36-valid-sudoku': () => import('./36-valid-sudoku.mdx'),
  '363-max-sum-of-rectangle-no-larger-than-k': () => import('./363-max-sum-of-rectangle-no-larger-than-k.mdx'),
  '37-sudoku-solver': () => import('./37-sudoku-solver.mdx'),
  '370-range-addition': () => import('./370-range-addition.mdx'),
  '380-insert-delete-getrandom-constant': () => import('./380-insert-delete-getrandom-constant.mdx'),
  '39-combination-sum': () => import('./39-combination-sum.mdx'),
  '394-decode-string': () => import('./394-decode-string.mdx'),
  '407-trapping-rain-water-ii': () => import('./407-trapping-rain-water-ii.mdx'),
  '41-first-missing-positive': () => import('./41-first-missing-positive.mdx'),
  '410-split-array-largest-sum': () => import('./410-split-array-largest-sum.mdx'),
  '416-partition-equal-subset-sum': () => import('./416-partition-equal-subset-sum.mdx'),
  '42-trapping-rain-water': () => import('./42-trapping-rain-water.mdx'),
  '424-longest-repeating-character-replacement': () => import('./424-longest-repeating-character-replacement.mdx'),
  '435-non-overlapping-intervals': () => import('./435-non-overlapping-intervals.mdx'),
  '438-find-all-anagrams-in-a-string': () => import('./438-find-all-anagrams-in-a-string.mdx'),
  '46-permutations': () => import('./46-permutations.mdx'),
  '460-lfu-cache': () => import('./460-lfu-cache.mdx'),
  '49-group-anagrams': () => import('./49-group-anagrams.mdx'),
  '497-random-point-in-non-overlapping-rectangles': () => import('./497-random-point-in-non-overlapping-rectangles.mdx'),
  '498-diagonal-traverse': () => import('./498-diagonal-traverse.mdx'),
  '50-pow': () => import('./50-pow.mdx'),
  '51-n-queens': () => import('./51-n-queens.mdx'),
  '518-coin-change-ii': () => import('./518-coin-change-ii.mdx'),
  '523-continuous-subarray-sum': () => import('./523-continuous-subarray-sum.mdx'),
  '525-contiguous-array': () => import('./525-contiguous-array.mdx'),
  '528-random-pick-with-weight': () => import('./528-random-pick-with-weight.mdx'),
  '53-maximum-subarray': () => import('./53-maximum-subarray.mdx'),
  '54-spiral-matrix': () => import('./54-spiral-matrix.mdx'),
  '542-01-matrix': () => import('./542-01-matrix.mdx'),
  '547-number-of-provinces': () => import('./547-number-of-provinces.mdx'),
  '56-merge-intervals': () => import('./56-merge-intervals.mdx'),
  '560-subarray-sum-equals-k': () => import('./560-subarray-sum-equals-k.mdx'),
  '57-insert-interval': () => import('./57-insert-interval.mdx'),
  '616-add-bold-tag-in-string': () => import('./616-add-bold-tag-in-string.mdx'),
  '64-minimum-path-sum': () => import('./64-minimum-path-sum.mdx'),
  '642-design-search-autocomplete-system': () => import('./642-design-search-autocomplete-system.mdx'),
  '648-replace-words': () => import('./648-replace-words.mdx'),
  '684-redundant-connection': () => import('./684-redundant-connection.mdx'),
  '69-sqrt': () => import('./69-sqrt.mdx'),
  '70-climbing-stairs': () => import('./70-climbing-stairs.mdx'),
  '710-random-pick-with-blacklist': () => import('./710-random-pick-with-blacklist.mdx'),
  '713-subarray-product-less-than-k': () => import('./713-subarray-product-less-than-k.mdx'),
  '72-edit-distance': () => import('./72-edit-distance.mdx'),
  '739-daily-temperatures': () => import('./739-daily-temperatures.mdx'),
  '743-network-delay-time': () => import('./743-network-delay-time.mdx'),
  '75-sort-colors': () => import('./75-sort-colors.mdx'),
  '76-minimum-window-substring': () => import('./76-minimum-window-substring.mdx'),
  '778-swim-in-rising-water': () => import('./778-swim-in-rising-water.mdx'),
  '787-cheapest-flights-within-k-stops': () => import('./787-cheapest-flights-within-k-stops.mdx'),
  '79-word-search': () => import('./79-word-search.mdx'),
  '794-valid-tic-tac-toe-state': () => import('./794-valid-tic-tac-toe-state.mdx'),
  '837-new-21-game': () => import('./837-new-21-game.mdx'),
  '84-largest-rectangle-in-histogram': () => import('./84-largest-rectangle-in-histogram.mdx'),
  '841-keys-and-rooms': () => import('./841-keys-and-rooms.mdx'),
  '875-koko-eating-bananas': () => import('./875-koko-eating-bananas.mdx'),
  '876-middle-of-the-linked-list': () => import('./876-middle-of-the-linked-list.mdx'),
  '889-construct-binary-tree-from-preorder-and-postorder-traversal': () => import('./889-construct-binary-tree-from-preorder-and-postorder-traversal.mdx'),
  '909-snakes-and-ladders': () => import('./909-snakes-and-ladders.mdx'),
  '918-maximum-sum-of-circular-subarray': () => import('./918-maximum-sum-of-circular-subarray.mdx'),
  '921-minimum-add-to-make-parentheses-valid': () => import('./921-minimum-add-to-make-parentheses-valid.mdx'),
  '937-k-closest-points-to-origin': () => import('./937-k-closest-points-to-origin.mdx'),
  '94-binary-tree-inorder-traversal': () => import('./94-binary-tree-inorder-traversal.mdx'),
  '974-subarray-sums-divisible-by-k': () => import('./974-subarray-sums-divisible-by-k.mdx'),
  '994-rotting-oranges': () => import('./994-rotting-oranges.mdx'),
} as const

export const problemSlugs = [
  '1-two-sum',
  '1000-minimum-cost-to-merge-stones',
  '1011-capacity-to-ship-packages-within-d-days',
  '102-binary-tree-level-order-traversal',
  '105-construct-binary-tree-from-preorder-and-inorder-traversal',
  '1094-car-pooling',
  '1143-longest-common-subsequence',
  '1162-as-far-from-land-as-possible',
  '120-triangle',
  '121-best-time-to-buy-and-sell-stock',
  '122-best-time-to-buy-and-sell-stock-ii',
  '123-best-time-to-buy-and-sell-stock-iii',
  '1235-maximum-profit-in-job-scheduling',
  '124-binary-tree-maximum-path-sum',
  '1249-minimum-remove-to-make-valid-parentheses',
  '127-word-ladder',
  '1275-find-winner-on-a-tic-tac-toe-game',
  '1293-shortest-path-in-a-grid-with-obstacles-elimination',
  '133-clone-graph',
  '136-single-number',
  '1406-stone-game-iii',
  '141-linked-list-cycle',
  '142-linked-list-cycle-ii',
  '144-binary-tree-preorder-traversal',
  '145-binary-tree-postorder-traversal',
  '146-lru-cache',
  '15-3sum',
  '1510-stone-game-iv',
  '1514-path-with-maximum-probability',
  '152-maximum-product-subarray',
  '153-find-minimum-in-rotated-sorted-array',
  '1547-minimum-cost-to-cut-a-stick',
  '1563-stone-game-v',
  '1570-dot-product-of-two-sparse-vectors',
  '1584-min-cost-to-connect-all-points',
  '1590-make-sum-divisible-by-p',
  '162-find-peak-element',
  '1631-path-with-minimum-effort',
  '188-best-time-to-buy-and-sell-stock-iv',
  '191-number-of-1-bits',
  '198-house-robber',
  '20-valid-parentheses',
  '200-number-of-islands',
  '207-course-schedule',
  '208-implement-trie-prefix-tree',
  '210-course-schedule-ii',
  '211-design-add-and-search-words-data-structure',
  '212-word-search-ii',
  '213-house-robber-ii',
  '2140-solving-questions-with-brainpower',
  '2145-count-the-hidden-sequences',
  '215-kth-largest-element-in-an-array',
  '22-generate-parentheses',
  '238-product-of-array-except-self',
  '2402-meeting-rooms-iii',
  '252-meeting-rooms',
  '253-meeting-rooms-ii',
  '256-paint-house',
  '265-paint-house-ii',
  '279-perfect-squares',
  '287-find-the-duplicate-number',
  '297-serialize-and-deserialize-binary-tree',
  '3-longest-substring-without-repeating-characters',
  '300-longest-increasing-subsequence',
  '301-remove-invalid-parentheses',
  '311-sparse-matrix-multiplication',
  '312-burst-balloons',
  '32-longest-valid-parentheses',
  '322-coin-change',
  '325-maximum-size-subarray-sum-equals-k',
  '33-search-in-rotated-sorted-array',
  '34-find-first-and-last-position-of-element-in-sorted-array',
  '347-top-k-frequent-elements',
  '348-design-tic-tac-toe',
  '35-search-insert-position',
  '36-valid-sudoku',
  '363-max-sum-of-rectangle-no-larger-than-k',
  '37-sudoku-solver',
  '370-range-addition',
  '380-insert-delete-getrandom-constant',
  '39-combination-sum',
  '394-decode-string',
  '407-trapping-rain-water-ii',
  '41-first-missing-positive',
  '410-split-array-largest-sum',
  '416-partition-equal-subset-sum',
  '42-trapping-rain-water',
  '424-longest-repeating-character-replacement',
  '435-non-overlapping-intervals',
  '438-find-all-anagrams-in-a-string',
  '46-permutations',
  '460-lfu-cache',
  '49-group-anagrams',
  '497-random-point-in-non-overlapping-rectangles',
  '498-diagonal-traverse',
  '50-pow',
  '51-n-queens',
  '518-coin-change-ii',
  '523-continuous-subarray-sum',
  '525-contiguous-array',
  '528-random-pick-with-weight',
  '53-maximum-subarray',
  '54-spiral-matrix',
  '542-01-matrix',
  '547-number-of-provinces',
  '56-merge-intervals',
  '560-subarray-sum-equals-k',
  '57-insert-interval',
  '616-add-bold-tag-in-string',
  '64-minimum-path-sum',
  '642-design-search-autocomplete-system',
  '648-replace-words',
  '684-redundant-connection',
  '69-sqrt',
  '70-climbing-stairs',
  '710-random-pick-with-blacklist',
  '713-subarray-product-less-than-k',
  '72-edit-distance',
  '739-daily-temperatures',
  '743-network-delay-time',
  '75-sort-colors',
  '76-minimum-window-substring',
  '778-swim-in-rising-water',
  '787-cheapest-flights-within-k-stops',
  '79-word-search',
  '794-valid-tic-tac-toe-state',
  '837-new-21-game',
  '84-largest-rectangle-in-histogram',
  '841-keys-and-rooms',
  '875-koko-eating-bananas',
  '876-middle-of-the-linked-list',
  '889-construct-binary-tree-from-preorder-and-postorder-traversal',
  '909-snakes-and-ladders',
  '918-maximum-sum-of-circular-subarray',
  '921-minimum-add-to-make-parentheses-valid',
  '937-k-closest-points-to-origin',
  '94-binary-tree-inorder-traversal',
  '974-subarray-sums-divisible-by-k',
  '994-rotting-oranges',
] as const

export type ProblemSlug = typeof problemSlugs[number]

