// Auto-generated component registry for problem MDX components

export const problemComponents = {
  '37-sudoku-solver': () => import('./37-sudoku-solver.mdx'),
  '1631-path-with-minimum-effort': () => import('./1631-path-with-minimum-effort.mdx'),
  '909-snakes-and-ladders': () => import('./909-snakes-and-ladders.mdx'),
  '1-two-sum': () => import('./1-two-sum.mdx'),
  '152-maximum-product-subarray': () => import('./152-maximum-product-subarray.mdx'),
  '1293-shortest-path-in-a-grid-with-obstacles-elimination': () => import('./1293-shortest-path-in-a-grid-with-obstacles-elimination.mdx'),
  '648-replace-words': () => import('./648-replace-words.mdx'),
  '394-decode-string': () => import('./394-decode-string.mdx'),
  '211-design-add-and-search-words-data-structure': () => import('./211-design-add-and-search-words-data-structure.mdx'),
  '1406-stone-game-iii': () => import('./1406-stone-game-iii.mdx'),
  '213-house-robber-ii': () => import('./213-house-robber-ii.mdx'),
  '875-koko-eating-bananas': () => import('./875-koko-eating-bananas.mdx'),
  '460-lfu-cache': () => import('./460-lfu-cache.mdx'),
  '133-clone-graph': () => import('./133-clone-graph.mdx'),
  '238-product-of-array-except-self': () => import('./238-product-of-array-except-self.mdx'),
  '523-continuous-subarray-sum': () => import('./523-continuous-subarray-sum.mdx'),
  '518-coin-change-ii': () => import('./518-coin-change-ii.mdx'),
  '416-partition-equal-subset-sum': () => import('./416-partition-equal-subset-sum.mdx'),
  '188-best-time-to-buy-and-sell-stock-iv': () => import('./188-best-time-to-buy-and-sell-stock-iv.mdx'),
  '20-valid-parentheses': () => import('./20-valid-parentheses.mdx'),
  '370-range-addition': () => import('./370-range-addition.mdx'),
  '120-triangle': () => import('./120-triangle.mdx'),
  '787-cheapest-flights-within-k-stops': () => import('./787-cheapest-flights-within-k-stops.mdx'),
  '363-max-sum-of-rectangle-no-larger-than-k': () => import('./363-max-sum-of-rectangle-no-larger-than-k.mdx'),
  '778-swim-in-rising-water': () => import('./778-swim-in-rising-water.mdx'),
  '525-contiguous-array': () => import('./525-contiguous-array.mdx'),
  '3-longest-substring-without-repeating-characters': () => import('./3-longest-substring-without-repeating-characters.mdx'),
  '51-n-queens': () => import('./51-n-queens.mdx'),
  '560-subarray-sum-equals-k': () => import('./560-subarray-sum-equals-k.mdx'),
  '1590-make-sum-divisible-by-p': () => import('./1590-make-sum-divisible-by-p.mdx'),
  '191-number-of-1-bits': () => import('./191-number-of-1-bits.mdx'),
  '70-climbing-stairs': () => import('./70-climbing-stairs.mdx'),
  '918-maximum-sum-of-circular-subarray': () => import('./918-maximum-sum-of-circular-subarray.mdx'),
  '215-kth-largest-element-in-an-array': () => import('./215-kth-largest-element-in-an-array.mdx'),
  '198-house-robber': () => import('./198-house-robber.mdx'),
  '146-lru-cache': () => import('./146-lru-cache.mdx'),
  '102-binary-tree-level-order-traversal': () => import('./102-binary-tree-level-order-traversal.mdx'),
  '974-subarray-sums-divisible-by-k': () => import('./974-subarray-sums-divisible-by-k.mdx'),
  '122-best-time-to-buy-and-sell-stock-ii': () => import('./122-best-time-to-buy-and-sell-stock-ii.mdx'),
  '33-search-in-rotated-sorted-array': () => import('./33-search-in-rotated-sorted-array.mdx'),
  '124-binary-tree-maximum-path-sum': () => import('./124-binary-tree-maximum-path-sum.mdx'),
  '1510-stone-game-iv': () => import('./1510-stone-game-iv.mdx'),
  '153-find-minimum-in-rotated-sorted-array': () => import('./153-find-minimum-in-rotated-sorted-array.mdx'),
  '994-rotting-oranges': () => import('./994-rotting-oranges.mdx'),
  '121-best-time-to-buy-and-sell-stock': () => import('./121-best-time-to-buy-and-sell-stock.mdx'),
  '53-maximum-subarray': () => import('./53-maximum-subarray.mdx'),
  '34-find-first-and-last-position-of-element-in-sorted-array': () => import('./34-find-first-and-last-position-of-element-in-sorted-array.mdx'),
  '76-minimum-window-substring': () => import('./76-minimum-window-substring.mdx'),
  '84-largest-rectangle-in-histogram': () => import('./84-largest-rectangle-in-histogram.mdx'),
  '136-single-number': () => import('./136-single-number.mdx'),
  '1514-path-with-maximum-probability': () => import('./1514-path-with-maximum-probability.mdx'),
  '79-word-search': () => import('./79-word-search.mdx'),
  '39-combination-sum': () => import('./39-combination-sum.mdx'),
  '542-01-matrix': () => import('./542-01-matrix.mdx'),
  '1011-capacity-to-ship-packages-within-d-days': () => import('./1011-capacity-to-ship-packages-within-d-days.mdx'),
  '208-implement-trie-prefix-tree': () => import('./208-implement-trie-prefix-tree.mdx'),
  '325-maximum-size-subarray-sum-equals-k': () => import('./325-maximum-size-subarray-sum-equals-k.mdx'),
  '2145-count-the-hidden-sequences': () => import('./2145-count-the-hidden-sequences.mdx'),
  '35-search-insert-position': () => import('./35-search-insert-position.mdx'),
  '46-permutations': () => import('./46-permutations.mdx'),
  '123-best-time-to-buy-and-sell-stock-iii': () => import('./123-best-time-to-buy-and-sell-stock-iii.mdx'),
  '347-top-k-frequent-elements': () => import('./347-top-k-frequent-elements.mdx'),
  '200-number-of-islands': () => import('./200-number-of-islands.mdx'),
  '2140-solving-questions-with-brainpower': () => import('./2140-solving-questions-with-brainpower.mdx'),
  '212-word-search-ii': () => import('./212-word-search-ii.mdx'),
  '713-subarray-product-less-than-k': () => import('./713-subarray-product-less-than-k.mdx'),
  '36-valid-sudoku': () => import('./36-valid-sudoku.mdx'),
  '743-network-delay-time': () => import('./743-network-delay-time.mdx'),
  '127-word-ladder': () => import('./127-word-ladder.mdx'),
} as const

export const problemSlugs = [
  '37-sudoku-solver',
  '1631-path-with-minimum-effort',
  '909-snakes-and-ladders',
  '1-two-sum',
  '152-maximum-product-subarray',
  '1293-shortest-path-in-a-grid-with-obstacles-elimination',
  '648-replace-words',
  '394-decode-string',
  '211-design-add-and-search-words-data-structure',
  '1406-stone-game-iii',
  '213-house-robber-ii',
  '875-koko-eating-bananas',
  '460-lfu-cache',
  '133-clone-graph',
  '238-product-of-array-except-self',
  '523-continuous-subarray-sum',
  '518-coin-change-ii',
  '416-partition-equal-subset-sum',
  '188-best-time-to-buy-and-sell-stock-iv',
  '20-valid-parentheses',
  '370-range-addition',
  '120-triangle',
  '787-cheapest-flights-within-k-stops',
  '363-max-sum-of-rectangle-no-larger-than-k',
  '778-swim-in-rising-water',
  '525-contiguous-array',
  '3-longest-substring-without-repeating-characters',
  '51-n-queens',
  '560-subarray-sum-equals-k',
  '1590-make-sum-divisible-by-p',
  '191-number-of-1-bits',
  '70-climbing-stairs',
  '918-maximum-sum-of-circular-subarray',
  '215-kth-largest-element-in-an-array',
  '198-house-robber',
  '146-lru-cache',
  '102-binary-tree-level-order-traversal',
  '974-subarray-sums-divisible-by-k',
  '122-best-time-to-buy-and-sell-stock-ii',
  '33-search-in-rotated-sorted-array',
  '124-binary-tree-maximum-path-sum',
  '1510-stone-game-iv',
  '153-find-minimum-in-rotated-sorted-array',
  '994-rotting-oranges',
  '121-best-time-to-buy-and-sell-stock',
  '53-maximum-subarray',
  '34-find-first-and-last-position-of-element-in-sorted-array',
  '76-minimum-window-substring',
  '84-largest-rectangle-in-histogram',
  '136-single-number',
  '1514-path-with-maximum-probability',
  '79-word-search',
  '39-combination-sum',
  '542-01-matrix',
  '1011-capacity-to-ship-packages-within-d-days',
  '208-implement-trie-prefix-tree',
  '325-maximum-size-subarray-sum-equals-k',
  '2145-count-the-hidden-sequences',
  '35-search-insert-position',
  '46-permutations',
  '123-best-time-to-buy-and-sell-stock-iii',
  '347-top-k-frequent-elements',
  '200-number-of-islands',
  '2140-solving-questions-with-brainpower',
  '212-word-search-ii',
  '713-subarray-product-less-than-k',
  '36-valid-sudoku',
  '743-network-delay-time',
  '127-word-ladder',
] as const

export type ProblemSlug = typeof problemSlugs[number]

