import { Code, SquareFunction } from "lucide-react"
import { NavigationItem } from "./routes"

export const PROBLEMS_ROUTES: NavigationItem[] = [
    {
        title: 'Problems', href: '/problems', icon: SquareFunction, color: "text-yellow-500", bgColor: "bg-yellow-500/10",
        children: [
            { title: '01 Matrix', href: '/problems/542-01-matrix', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: '3sum', href: '/problems/15-3sum', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Add Bold Tag in String', href: '/problems/616-add-bold-tag-in-string', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'As Far from Land as Possible', href: '/problems/1162-as-far-from-land-as-possible', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Best Time to Buy and Sell Stock', href: '/problems/121-best-time-to-buy-and-sell-stock', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Best Time to Buy and Sell Stock II', href: '/problems/122-best-time-to-buy-and-sell-stock-ii', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Best Time to Buy and Sell Stock III', href: '/problems/123-best-time-to-buy-and-sell-stock-iii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Best Time to Buy and Sell Stock IV', href: '/problems/188-best-time-to-buy-and-sell-stock-iv', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Binary Tree Inorder Traversal', href: '/problems/94-binary-tree-inorder-traversal', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Binary Tree Level Order Traversal', href: '/problems/102-binary-tree-level-order-traversal', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Binary Tree Maximum Path Sum', href: '/problems/124-binary-tree-maximum-path-sum', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Binary Tree Postorder Traversal', href: '/problems/145-binary-tree-postorder-traversal', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Binary Tree Preorder Traversal', href: '/problems/144-binary-tree-preorder-traversal', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Burst Balloons', href: '/problems/312-burst-balloons', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Capacity To Ship Packages Within D Days', href: '/problems/1011-capacity-to-ship-packages-within-d-days', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Car Pooling', href: '/problems/1094-car-pooling', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Cheapest Flights Within K Stops', href: '/problems/787-cheapest-flights-within-k-stops', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Climbing Stairs', href: '/problems/70-climbing-stairs', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Clone Graph', href: '/problems/133-clone-graph', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Coin Change', href: '/problems/322-coin-change', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Coin Change II', href: '/problems/518-coin-change-ii', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Combination Sum', href: '/problems/39-combination-sum', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Construct Binary Tree from Preorder and Inorder Traversal', href: '/problems/105-construct-binary-tree-from-preorder-and-inorder-traversal', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Construct Binary Tree from Preorder and Postorder Traversal', href: '/problems/889-construct-binary-tree-from-preorder-and-postorder-traversal', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Contiguous Array', href: '/problems/525-contiguous-array', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Continuous Subarray Sum', href: '/problems/523-continuous-subarray-sum', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Count the Hidden Sequences', href: '/problems/2145-count-the-hidden-sequences', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Course Schedule', href: '/problems/207-course-schedule', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Course Schedule II', href: '/problems/210-course-schedule-ii', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Decode String', href: '/problems/394-decode-string', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Design Add and Search Words Data Structure', href: '/problems/211-design-add-and-search-words-data-structure', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Design Search Autocomplete System', href: '/problems/642-design-search-autocomplete-system', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Design Tic-Tac-Toe', href: '/problems/348-design-tic-tac-toe', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Diagonal Traverse', href: '/problems/498-diagonal-traverse', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Dot Product of Two Sparse Vectors', href: '/problems/1570-dot-product-of-two-sparse-vectors', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Edit Distance', href: '/problems/72-edit-distance', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Find First and Last Position of Element in Sorted Array', href: '/problems/34-find-first-and-last-position-of-element-in-sorted-array', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Find Minimum in Rotated Sorted Array', href: '/problems/153-find-minimum-in-rotated-sorted-array', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Find Peak Element', href: '/problems/162-find-peak-element', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Find Winner on a Tic Tac Toe Game', href: '/problems/1275-find-winner-on-a-tic-tac-toe-game', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'House Robber', href: '/problems/198-house-robber', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'House Robber II', href: '/problems/213-house-robber-ii', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Implement Trie (Prefix Tree)', href: '/problems/208-implement-trie-prefix-tree', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Insert Delete GetRandom O(1)', href: '/problems/380-insert-delete-getrandom-constant', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Insert Interval', href: '/problems/57-insert-interval', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Keys and Rooms', href: '/problems/841-keys-and-rooms', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Koko Eating Bananas', href: '/problems/875-koko-eating-bananas', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Kth Largest Element In An Array', href: '/problems/215-kth-largest-element-in-an-array', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Largest Rectangle in Histogram', href: '/problems/84-largest-rectangle-in-histogram', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'LFU Cache', href: '/problems/460-lfu-cache', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Longest Common Subsequence', href: '/problems/1143-longest-common-subsequence', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Longest Increasing Subsequence', href: '/problems/300-longest-increasing-subsequence', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Longest Repeating Character Replacement', href: '/problems/424-longest-repeating-character-replacement', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Longest Substring Without Repeating Characters', href: '/problems/3-longest-substring-without-repeating-characters', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'LRU Cache', href: '/problems/146-lru-cache', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Make Sum Divisible by P', href: '/problems/1590-make-sum-divisible-by-p', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Max Sum of Rectangle No Larger Than K', href: '/problems/363-max-sum-of-rectangle-no-larger-than-k', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Maximum Product Subarray', href: '/problems/152-maximum-product-subarray', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Maximum Profit in Job Scheduling', href: '/problems/1235-maximum-profit-in-job-scheduling', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Maximum Size Subarray Sum Equals k', href: '/problems/325-maximum-size-subarray-sum-equals-k', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Maximum Subarray', href: '/problems/53-maximum-subarray', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Maximum Sum of Circular Subarray', href: '/problems/918-maximum-sum-of-circular-subarray', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Meeting Rooms', href: '/problems/252-meeting-rooms', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Meeting Rooms II', href: '/problems/253-meeting-rooms-ii', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Meeting Rooms III', href: '/problems/2402-meeting-rooms-iii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Merge Intervals', href: '/problems/56-merge-intervals', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Min Cost to Connect All Points', href: '/problems/1584-min-cost-to-connect-all-points', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Minimum Cost to Cut a Stick', href: '/problems/1547-minimum-cost-to-cut-a-stick', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Minimum Cost to Merge Stones', href: '/problems/1000-minimum-cost-to-merge-stones', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Minimum Path Sum', href: '/problems/64-minimum-path-sum', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Minimum Window Substring', href: '/problems/76-minimum-window-substring', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Most Points Solving Questions With Brainpower', href: '/problems/2140-solving-questions-with-brainpower', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'N-Queens', href: '/problems/51-n-queens', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Network Delay Time', href: '/problems/743-network-delay-time', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'New 21 Game', href: '/problems/837-new-21-game', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Non-overlapping Intervals', href: '/problems/435-non-overlapping-intervals', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Number of 1 Bits', href: '/problems/191-number-of-1-bits', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Number of Islands', href: '/problems/200-number-of-islands', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Number of Provinces', href: '/problems/547-number-of-provinces', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Number of Subarrays with Product Less Than K', href: '/problems/713-subarray-product-less-than-k', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Paint House', href: '/problems/256-paint-house', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Paint House II', href: '/problems/265-paint-house-ii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Partition Equal Subset Sum', href: '/problems/416-partition-equal-subset-sum', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Path with Maximum Probability', href: '/problems/1514-path-with-maximum-probability', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Path With Minimum Effort', href: '/problems/1631-path-with-minimum-effort', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Permutations', href: '/problems/46-permutations', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Pow(x, n)', href: '/problems/50-pow', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Product of Array Except Self', href: '/problems/238-product-of-array-except-self', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Random Pick with Blacklist', href: '/problems/710-random-pick-with-blacklist', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Random Pick with Weight', href: '/problems/528-random-pick-with-weight', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Random Point in Non-overlapping Rectangles', href: '/problems/497-random-point-in-non-overlapping-rectangles', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Range Addition', href: '/problems/370-range-addition', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Redundant Connection', href: '/problems/684-redundant-connection', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Remove Invalid Parentheses', href: '/problems/301-remove-invalid-parentheses', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Replace Words', href: '/problems/648-replace-words', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Rotting Oranges', href: '/problems/994-rotting-oranges', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Search In Rotated Sorted Array', href: '/problems/33-search-in-rotated-sorted-array', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Search Insert Position', href: '/problems/35-search-insert-position', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Serialize and Deserialize Binary Tree', href: '/problems/297-serialize-and-deserialize-binary-tree', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Shortest Path in a Grid with Obstacles Elimination', href: '/problems/1293-shortest-path-in-a-grid-with-obstacles-elimination', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Single Number', href: '/problems/136-single-number', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Snakes and Ladders', href: '/problems/909-snakes-and-ladders', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Sparse Matrix Multiplication', href: '/problems/311-sparse-matrix-multiplication', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Spiral Matrix', href: '/problems/54-spiral-matrix', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Split Array Largest Sum', href: '/problems/410-split-array-largest-sum', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Sqrt(x)', href: '/problems/69-sqrt', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Stone Game III', href: '/problems/1406-stone-game-iii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Stone Game IV', href: '/problems/1510-stone-game-iv', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Stone Game V', href: '/problems/1563-stone-game-v', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Subarray Sum Equals K', href: '/problems/560-subarray-sum-equals-k', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Subarray Sums Divisible by K', href: '/problems/974-subarray-sums-divisible-by-k', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Sudoku Solver', href: '/problems/37-sudoku-solver', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Swim in Rising Water', href: '/problems/778-swim-in-rising-water', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Top K Frequent Elements', href: '/problems/347-top-k-frequent-elements', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Trapping Rain Water', href: '/problems/42-trapping-rain-water', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Trapping Rain Water II', href: '/problems/407-trapping-rain-water-ii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Triangle Minimum Path Sum', href: '/problems/120-triangle', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Two Sum', href: '/problems/1-two-sum', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Valid Parentheses', href: '/problems/20-valid-parentheses', icon: Code, color: "text-green-500", bgColor: "bg-green-500/10" },
            { title: 'Valid Sudoku', href: '/problems/36-valid-sudoku', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Valid Tic-Tac-Toe State', href: '/problems/794-valid-tic-tac-toe-state', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Word Ladder', href: '/problems/127-word-ladder', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
            { title: 'Word Search', href: '/problems/79-word-search', icon: Code, color: "text-orange-500", bgColor: "bg-orange-500/10" },
            { title: 'Word Search II', href: '/problems/212-word-search-ii', icon: Code, color: "text-red-500", bgColor: "bg-red-500/10" },
        ],
    },
]
