// export const COMMON_WORDS = [
//   'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
//   'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
//   'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
//   'argue', 'arise', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'awake', 'award',
//   'aware', 'badly', 'baker', 'bases', 'basic', 'beach', 'began', 'begin', 'being', 'below',
//   'bench', 'billy', 'birth', 'black', 'blame', 'blind', 'block', 'blood', 'board', 'boost',
//   'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brief',
//   'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'calm', 'came',
//   'canal', 'candy', 'carry', 'catch', 'cause', 'chain', 'chair', 'chaos', 'charm', 'chart',
//   'chase', 'cheap', 'check', 'chest', 'chief', 'child', 'china', 'chose', 'civil', 'claim',
//   'class', 'clean', 'clear', 'click', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast',
//   'could', 'count', 'court', 'cover', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross',
//   'crowd', 'crown', 'crude', 'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death',
//   'debut', 'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream',
//   'dress', 'drill', 'drink', 'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight',
//   'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every',
//   'exact', 'exist', 'extra', 'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty',
//   'fight', 'final', 'first', 'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force',
//   'forth', 'forty', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit',
//   'fully', 'funny', 'giant', 'given', 'glass', 'globe', 'going', 'grace', 'grade', 'grand',
//   'grant', 'grass', 'grave', 'great', 'green', 'gross', 'group', 'grown', 'guard', 'guess',
//   'guest', 'guide', 'happy', 'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel',
//   'house', 'human', 'ideal', 'image', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy',
//   'joint', 'jones', 'judge', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer',
//   'learn', 'lease', 'least', 'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links',
//   'lives', 'local', 'loose', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker',
//   'march', 'maria', 'match', 'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor',
//   'minus', 'mixed', 'model', 'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth',
//   'moved', 'movie', 'music', 'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted',
//   'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint',
//   'panel', 'paper', 'party', 'peace', 'peter', 'phase', 'phone', 'photo', 'piano', 'piece',
//   'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power',
//   'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove',
//   'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach',
//   'ready', 'realm', 'rebel', 'refer', 'relax', 'repay', 'reply', 'right', 'rigid', 'rival',
//   'river', 'robin', 'roger', 'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale',
//   'scene', 'scope', 'score', 'sense', 'serve', 'seven', 'shall', 'shape', 'share', 'sharp',
//   'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown',
//   'sides', 'sight', 'silly', 'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide',
//   'small', 'smart', 'smile', 'smith', 'smoke', 'snap', 'snow', 'solid', 'solve', 'sorry',
//   'sound', 'south', 'space', 'spare', 'speak', 'speed', 'spend', 'spent', 'split', 'spoke',
//   'sport', 'staff', 'stage', 'stake', 'stand', 'start', 'state', 'steam', 'steel', 'steep',
//   'steer', 'stern', 'stick', 'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story',
//   'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'table',
//   'taken', 'taste', 'taxes', 'teach', 'teens', 'teeth', 'terry', 'texas', 'thank', 'theft',
//   'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those', 'three',
//   'threw', 'throw', 'thumb', 'tight', 'times', 'tired', 'title', 'today', 'topic', 'total',
//   'touch', 'tough', 'tower', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'treat',
//   'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'truck', 'truly', 'trunk', 'trust',
//   'truth', 'twice', 'uncle', 'under', 'undue', 'union', 'unity', 'until', 'upper', 'upset',
//   'urban', 'usage', 'usual', 'valid', 'value', 'video', 'virus', 'visit', 'vital', 'vocal',
//   'voice', 'waste', 'watch', 'water', 'wheel', 'where', 'which', 'while', 'white', 'whole',
//   'whose', 'woman', 'women', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'write',
//   'wrong', 'wrote', 'young', 'youth'
// ];

// export const FIVE_LETTER_WORDS = [
//   'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
//   'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
//   'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
//   'argue', 'arise', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'awake', 'award',
//   'aware', 'badly', 'baker', 'bases', 'basic', 'beach', 'began', 'begin', 'being', 'below',
//   'bench', 'billy', 'birth', 'black', 'blame', 'blind', 'block', 'blood', 'board', 'boost',
//   'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brief',
//   'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'candy', 'carry',
//   'catch', 'cause', 'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check',
//   'chest', 'chief', 'child', 'china', 'chose', 'civil', 'claim', 'class', 'clean', 'clear',
//   'click', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court',
//   'cover', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd', 'crown', 'crude',
//   'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut', 'delay', 'depth',
//   'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream', 'dress', 'drill', 'drink',
//   'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite', 'empty', 'enemy',
//   'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra',
//   'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final', 'first',
//   'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum',
//   'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny', 'giant',
//   'given', 'glass', 'globe', 'going', 'grace', 'grade', 'grand', 'grant', 'grass', 'grave',
//   'great', 'green', 'gross', 'group', 'grown', 'guard', 'guess', 'guest', 'guide', 'happy',
//   'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel', 'house', 'human', 'ideal',
//   'image', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy', 'joint', 'jones', 'judge',
//   'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn', 'lease', 'least',
//   'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links', 'lives', 'local', 'loose',
//   'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'maria', 'match',
//   'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model',
//   'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie', 'music',
//   'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse', 'occur',
//   'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint', 'panel', 'paper', 'party',
//   'peace', 'peter', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'place',
//   'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power', 'press', 'price', 'pride',
//   'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove', 'queen', 'quick', 'quiet',
//   'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'ready', 'realm', 'rebel',
//   'refer', 'relax', 'repay', 'reply', 'right', 'rigid', 'rival', 'river', 'robin', 'roger',
//   'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score',
//   'sense', 'serve', 'seven', 'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell',
//   'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sides', 'sight', 'silly',
//   'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile',
//   'smith', 'smoke', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak',
//   'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand',
//   'start', 'state', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick', 'still', 'stock',
//   'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck', 'study', 'stuff', 'style',
//   'sugar', 'suite', 'super', 'sweet', 'table', 'taken', 'taste', 'taxes', 'teach', 'teens',
//   'teeth', 'terry', 'texas', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick',
//   'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb', 'tight', 'times',
//   'tired', 'title', 'today', 'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade',
//   'trail', 'train', 'trait', 'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried',
//   'tries', 'truck', 'truly', 'trunk', 'trust', 'truth', 'twice', 'uncle', 'under', 'undue',
//   'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value',
//   'video', 'virus', 'visit', 'vital', 'vocal', 'voice', 'waste', 'watch', 'water', 'wheel',
//   'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'women', 'world', 'worry',
//   'worse', 'worst', 'worth', 'would', 'write', 'wrong', 'wrote', 'young', 'youth'
// ] as const;

// export const WORD_DEFINITIONS = {
//   'about': 'concerning; regarding; approximately',
//   'above': 'higher than; more than; over',
//   'abuse': 'treat with cruelty or violence; misuse',
//   'actor': 'person who acts in plays or movies',
//   'acute': 'very sharp or severe; having a sharp point',
//   'admit': 'confess to be true; allow entry',
//   'adopt': 'take in and raise as one\'s own child',
//   'adult': 'fully grown person; mature',
//   'after': 'following in time or place',
//   'again': 'once more; another time',
//   'agent': 'person who acts on behalf of another',
//   'agree': 'have the same opinion; consent',
//   'ahead': 'in front; in advance',
//   'alarm': 'warning signal; sudden fear',
//   'album': 'book for photographs; music recording',
//   'alert': 'watchful; quick to notice',
//   'alike': 'similar; in the same way',
//   'alive': 'living; not dead',
//   'allow': 'permit; give permission',
//   'alone': 'without others; solitary',
//   'along': 'by the side of; together with',
//   'alter': 'change; modify',
//   'among': 'in the midst of; surrounded by',
//   'anger': 'strong feeling of displeasure',
//   'angle': 'space between two intersecting lines',
//   'angry': 'feeling or showing anger',
//   'apart': 'separated; at a distance',
//   'apple': 'round fruit that grows on trees',
//   'apply': 'put to use; request formally',
//   'arena': 'area for sports or entertainment',
//   'argue': 'give reasons; quarrel',
//   'arise': 'get up; come into being',
//   'array': 'impressive display; arrangement',
//   'aside': 'to one side; apart',
//   'asset': 'valuable possession; advantage',
//   'audio': 'relating to sound or hearing',
//   'audit': 'official examination of accounts',
//   'avoid': 'keep away from; prevent',
//   'awake': 'not asleep; alert',
//   'award': 'give as prize; prize given',
//   'aware': 'having knowledge; conscious',
//   'badly': 'in a bad manner; severely',
//   'baker': 'person who bakes bread and cakes',
//   'bases': 'plural of base; foundations',
//   'basic': 'fundamental; essential',
//   'beach': 'sandy shore by the sea',
//   'began': 'past tense of begin',
//   'begin': 'start; commence',
//   'being': 'existence; living creature',
//   'below': 'under; at a lower level',
//   'bench': 'long seat; judge\'s seat',
//   'billy': 'male goat; common name',
//   'birth': 'act of being born',
//   'black': 'darkest color; without light',
//   'blame': 'hold responsible; fault',
//   'blind': 'unable to see; without sight',
//   'block': 'solid piece; obstruct',
//   'blood': 'red fluid in body',
//   'board': 'flat piece of wood; group of directors',
//   'boost': 'help increase; push upward',
//   'booth': 'small enclosed space',
//   'bound': 'tied up; certain to happen',
//   'brain': 'organ of thought in head',
//   'brand': 'trademark; type of product',
//   'brass': 'yellow metal; boldness',
//   'brave': 'showing courage; fearless',
//   'bread': 'food made from flour',
//   'break': 'separate into pieces; pause',
//   'breed': 'produce offspring; type',
//   'brief': 'short; lasting a short time',
//   'bring': 'carry to this place',
//   'broad': 'wide; extensive',
//   'broke': 'having no money; past tense of break',
//   'brown': 'color of earth or wood',
//   'build': 'construct; create by assembling',
//   'built': 'past tense of build; constructed',
//   'buyer': 'person who purchases',
//   'cable': 'thick rope; wire for electricity',
//   'candy': 'sweet confection',
//   'carry': 'transport; bear the weight of',
//   'catch': 'capture; grab hold of',
//   'cause': 'reason; bring about',
//   'chain': 'series of connected links',
//   'chair': 'seat with back; lead a meeting',
//   'chaos': 'complete disorder',
//   'charm': 'attractiveness; magical power',
//   'chart': 'map; graph showing information',
//   'chase': 'pursue; run after',
//   'cheap': 'low in price; of poor quality',
//   'check': 'examine; verify; restraint',
//   'chest': 'front of body; storage box',
//   'chief': 'leader; main; most important',
//   'child': 'young human being',
//   'china': 'fine porcelain; country in Asia',
//   'chose': 'past tense of choose',
//   'civil': 'relating to citizens; polite',
//   'claim': 'assert; demand as one\'s right',
//   'class': 'group of students; social rank',
//   'clean': 'free from dirt; pure',
//   'clear': 'transparent; easy to understand',
//   'click': 'short sharp sound',
//   'climb': 'go up; ascend',
//   'clock': 'device for measuring time',
//   'close': 'shut; near; end',
//   'cloud': 'mass of water vapor in sky',
//   'coach': 'trainer; vehicle; teach',
//   'coast': 'seashore; move without effort'
// } as const satisfies Record<string, string>;

// export const SPELLING_BEE_WORDS = [
//   'about', 'actor', 'album', 'alone', 'angle', 'angry', 'apply', 'argue', 'asset', 'audio',
//   'awake', 'badge', 'basic', 'beach', 'began', 'being', 'bench', 'black', 'blade', 'blank',
//   'block', 'blood', 'board', 'boost', 'bound', 'brain', 'brand', 'brave', 'bread', 'break',
//   'breed', 'brief', 'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable',
//   'canal', 'candy', 'carry', 'catch', 'cause', 'chain', 'chair', 'chaos', 'charm', 'chart',
//   'chase', 'cheap', 'check', 'chest', 'chief', 'child', 'china', 'chose', 'civil', 'claim',
//   'class', 'clean', 'clear', 'click', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast',
//   'count', 'court', 'cover', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd',
//   'crown', 'crude', 'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut',
//   'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream', 'dress',
//   'drill', 'drink', 'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite',
//   'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact',
//   'exist', 'extra', 'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight',
//   'final', 'first', 'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth',
//   'forty', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit', 'fully',
//   'funny', 'giant', 'given', 'glass', 'globe', 'going', 'grace', 'grade', 'grand', 'grant',
//   'grass', 'grave', 'great', 'green', 'gross', 'group', 'grown', 'guard', 'guess', 'guest',
//   'guide', 'happy', 'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel', 'house',
//   'human', 'ideal', 'image', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy', 'joint',
//   'jones', 'judge', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
//   'lease', 'least', 'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links', 'lives',
//   'local', 'loose', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march',
//   'maria', 'match', 'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus',
//   'mixed', 'model', 'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved',
//   'movie', 'music', 'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel',
//   'nurse', 'occur', 'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint', 'panel',
//   'paper', 'party', 'peace', 'peter', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot',
//   'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power', 'press',
//   'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove', 'queen',
//   'quick', 'quiet', 'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'ready',
//   'realm', 'rebel', 'refer', 'relax', 'repay', 'reply', 'right', 'rigid', 'rival', 'river',
//   'robin', 'roger', 'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale', 'scene',
//   'scope', 'score', 'sense', 'serve', 'seven', 'shall', 'shape', 'share', 'sharp', 'sheet',
//   'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sides',
//   'sight', 'silly', 'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small',
//   'smart', 'smile', 'smith', 'smoke', 'solid', 'solve', 'sorry', 'sound', 'south', 'space',
//   'spare', 'speak', 'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage',
//   'stake', 'stand', 'start', 'state', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick',
//   'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck', 'study',
//   'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'table', 'taken', 'taste', 'taxes',
//   'teach', 'teens', 'teeth', 'terry', 'texas', 'thank', 'theft', 'their', 'theme', 'there',
//   'these', 'thick', 'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb',
//   'tight', 'times', 'tired', 'title', 'today', 'topic', 'total', 'touch', 'tough', 'tower',
//   'track', 'trade', 'trail', 'train', 'trait', 'trash', 'treat', 'trend', 'trial', 'tribe',
//   'trick', 'tried', 'tries', 'truck', 'truly', 'trunk', 'trust', 'truth', 'twice', 'uncle',
//   'under', 'undue', 'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual',
//   'valid', 'value', 'video', 'virus', 'visit', 'vital', 'vocal', 'voice', 'waste', 'watch',
//   'water', 'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'women',
//   'world', 'worry', 'worse', 'worst', 'worth', 'would', 'write', 'wrong', 'wrote', 'young', 'youth'
// ] as const;